/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AssemblyRouteImport } from './routes/assembly'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as AdminTransparencyRouteImport } from './routes/admin.transparency'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminBoardRouteImport } from './routes/admin.board'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyRoute = AssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/admin/volunteers',
  path: '/admin/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransparencyRoute = AdminTransparencyRouteImport.update({
  id: '/admin/transparency',
  path: '/admin/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBoardRoute = AdminBoardRouteImport.update({
  id: '/admin/board',
  path: '/admin/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assembly': typeof AssemblyRoute
  '/board': typeof BoardRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/statistics': typeof StatisticsRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/transparency': typeof AdminTransparencyRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assembly': typeof AssemblyRoute
  '/board': typeof BoardRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/statistics': typeof StatisticsRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/transparency': typeof AdminTransparencyRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assembly': typeof AssemblyRoute
  '/board': typeof BoardRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
  '/statistics': typeof StatisticsRoute
  '/transparency': typeof TransparencyRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/transparency': typeof AdminTransparencyRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assembly'
    | '/board'
    | '/careers'
    | '/contact'
    | '/news'
    | '/programs'
    | '/statistics'
    | '/transparency'
    | '/volunteer'
    | '/admin/board'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/statistics'
    | '/admin/transparency'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assembly'
    | '/board'
    | '/careers'
    | '/contact'
    | '/news'
    | '/programs'
    | '/statistics'
    | '/transparency'
    | '/volunteer'
    | '/admin/board'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/statistics'
    | '/admin/transparency'
    | '/admin/volunteers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/assembly'
    | '/board'
    | '/careers'
    | '/contact'
    | '/news'
    | '/programs'
    | '/statistics'
    | '/transparency'
    | '/volunteer'
    | '/admin/board'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/news'
    | '/admin/programs'
    | '/admin/statistics'
    | '/admin/transparency'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssemblyRoute: typeof AssemblyRoute
  BoardRoute: typeof BoardRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  ProgramsRoute: typeof ProgramsRoute
  StatisticsRoute: typeof StatisticsRoute
  TransparencyRoute: typeof TransparencyRoute
  VolunteerRoute: typeof VolunteerRoute
  AdminBoardRoute: typeof AdminBoardRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminTransparencyRoute: typeof AdminTransparencyRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly': {
      id: '/assembly'
      path: '/assembly'
      fullPath: '/assembly'
      preLoaderRoute: typeof AssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/admin/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transparency': {
      id: '/admin/transparency'
      path: '/admin/transparency'
      fullPath: '/admin/transparency'
      preLoaderRoute: typeof AdminTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/board': {
      id: '/admin/board'
      path: '/admin/board'
      fullPath: '/admin/board'
      preLoaderRoute: typeof AdminBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssemblyRoute: AssemblyRoute,
  BoardRoute: BoardRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  ProgramsRoute: ProgramsRoute,
  StatisticsRoute: StatisticsRoute,
  TransparencyRoute: TransparencyRoute,
  VolunteerRoute: VolunteerRoute,
  AdminBoardRoute: AdminBoardRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminTransparencyRoute: AdminTransparencyRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
